---
kubernetes_release: v1.34
kubernetes_admin_conf_path: /etc/kubernetes/admin.conf
kubernetes_cri_socket: unix:///run/containerd/containerd.sock
kubernetes_pod_network_cidr: 192.168.0.0/16
kubernetes_node_ready_timeout: 300s
kubeadm_image_pull_timeout: 600s
kubeadm_init_timeout: 600s
local_registry_enabled: false
use_upstream_calico_images: true
aws_ecr_enabled: true
node_local_storage_size_gib: 20
metrics_server_wait_timeout: 300s
kubernetes_admin_user: ubuntu
kubernetes_admin_group: ubuntu
kubernetes_admin_home: /home/ubuntu
