ssh:
  config_path: ../../../../.local/private-dev/ssh_config
  key_path: ~/.ssh/medikong-private-dev
  passphrase: ""
  user: lab-bum4496-833cff
  node1:
    host: external.terminal-lab.kr
    port: 41280
  peers:
    node2: 10.0.3.45
    node3: 10.0.1.246
    node4: 10.0.2.233
    node5: 10.0.2.250
    node6: 10.0.3.196
cluster:
  env: private-dev
  inventory: ./inventories/lab/private-dev.ini
  server_os: el9
  ansible_flags: ""
  run_private_dev_secrets: false
  run_ecr_secret: false
argocd:
  namespace: argocd
  install_manifest_url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  root_application_url: https://raw.githubusercontent.com/TicketMong/gitops/main/argo/applications/private-dev/root.yaml
  server_ready_timeout: 300s
  controller_ready_timeout: 300s
  root_application_name: medikong-private-dev-apps
