---
- name: Verify aws-dev Kubernetes cluster
  hosts: "control_plane[0]"
  become: true
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Verify Kubernetes cluster readiness
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: verify
