---
- name: Prepare private-dev Kubernetes hosts
  hosts: k8s_cluster
  become: true
  gather_facts: true
  vars_files:
    - ../group_vars/all.yml
  roles:
    - base-os
    - containerd
    - kubernetes
    - role: cni
      tasks_from: prepare

- name: Initialize private-dev primary control plane
  hosts: "control_plane[0]"
  become: true
  gather_facts: true
  vars_files:
    - ../group_vars/all.yml
  roles:
    - control-plane
    - cni

- name: Join private-dev additional control planes
  hosts: "control_plane[1:]"
  serial: 1
  become: true
  gather_facts: true
  vars_files:
    - ../group_vars/all.yml
  roles:
    - role: control-plane
      tasks_from: join

- name: Join private-dev workers
  hosts: workers
  become: true
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  roles:
    - worker

- name: Finish private-dev Kubernetes services
  hosts: "control_plane[0]"
  become: true
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  roles:
    - role: cni
      tasks_from: ready
    - role: kubernetes
      tasks_from: metrics
