---
- name: Verify private-dev Kubernetes cluster
  hosts: "control_plane[0]"
  become: true
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  roles:
    - role: kubernetes
      tasks_from: verify
